ENT.Base 			= "npc_vj_hlr1_alienslave"
ENT.Type 			= "ai"
ENT.PrintName 		= "Alien Grunt"
ENT.Author 			= "DrVrej"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Category		= "Half-Life Resurgence"